Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -56,20 +56,24 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y google-chrome-stable
           node crudTest.js
-          exit_code=$?
-  
-          if [ $exit_code -ne 0 ]; then
-            echo "Selenium tests failed. Raising a bug "
-            
+      - name: Check Selenium tests status
+        id: check_tests
+        run: exit_code=$?; echo "::set-output name=exit_code::$exit_code"
+
+      - name: Report status and raise bug if tests failed
+        run: |
+          if [ "${{ steps.check_tests.outputs.exit_code }}" -ne 0 ]; then
+            echo "Selenium tests failed. Raising a bug."
+
             - name: GitHub Action to create an Azure DevOps Bug Workitem when a workflow fails
-              uses: stefanstranger/azuredevops-bug-action@1.1
+               uses: stefanstranger/azuredevops-bug-action@1.1
               with:
-                OrganizationName: ${{secrets.ORGNAME}}
-                PAT: ${{secrets.PAT}}
+                OrganizationName: your_organization
+                PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
                 ProjectName: raise_a_bug
                 AreaPath: selenium_tests
                 IterationPath: frontend
-                GithubToken: ${{secrets.GITHUB_TOKEN}}
+                GithubToken: ${{ secrets.GITHUB_TOKEN }}
           else
             echo "Selenium tests passed."
           fi
